version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dong2605
      MYSQL_DATABASE: phone
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
